CREATE SCHEMA IF NOT EXISTS "game-table-booking";

-- Table: game-table-booking.booking

-- DROP TABLE IF EXISTS "game-table-booking".booking;

CREATE TABLE IF NOT EXISTS "game-table-booking".booking
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game character varying COLLATE pg_catalog."default",
    "userId" character varying COLLATE pg_catalog."default",
    username character varying COLLATE pg_catalog."default",
    points integer,
    description character varying COLLATE pg_catalog."default",
    status character varying COLLATE pg_catalog."default",
    "reminderEnabled" boolean,
    "dateTime" timestamp without time zone,
    players character varying[] COLLATE pg_catalog."default"
);

-- Table: game-table-booking.discord_rate_limit
-- Single-row table persisting the Discord API backoff window across process restarts
-- (e.g. Render free tier spinning the service down/up), since in-memory state doesn't survive that.

CREATE TABLE IF NOT EXISTS "game-table-booking".discord_rate_limit
(
    id smallint PRIMARY KEY,
    "blockedUntil" timestamp with time zone NOT NULL
);
