CREATE SCHEMA IF NOT EXISTS "game-table-booking";

-- Table: game-table-booking.booking

-- DROP TABLE IF EXISTS "game-table-booking".booking;

CREATE TABLE IF NOT EXISTS "game-table-booking".booking
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game character varying COLLATE pg_catalog."default",
    "userId" character varying COLLATE pg_catalog."default",
    username character varying COLLATE pg_catalog."default",
    points integer,
    description character varying COLLATE pg_catalog."default",
    status character varying COLLATE pg_catalog."default",
    "reminderEnabled" boolean,
    "dateTime" timestamp without time zone,
    players character varying[] COLLATE pg_catalog."default"
);