// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hanksha/tbz-booking-system-backend/booking (interfaces: BookingRepository)
//
// Generated by this command:
//
//      mockgen . BookingRepository
//

// Package booking_mocks is a generated GoMock package.
package booking_mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	"github.com/hanksha/tbz-booking-system-backend/booking"
	gomock "go.uber.org/mock/gomock"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
	isgomock struct{}
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// GetActiveBookings mocks base method.
func (m *MockBookingRepository) GetActiveBookings(ctx context.Context) ([]booking.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveBookings", ctx)
	ret0, _ := ret[0].([]booking.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveBookings indicates an expected call of GetActiveBookings.
func (mr *MockBookingRepositoryMockRecorder) GetActiveBookings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveBookings", reflect.TypeOf((*MockBookingRepository)(nil).GetActiveBookings), ctx)
}

// GetBookingByID mocks base method.
func (m *MockBookingRepository) GetBookingByID(ctx context.Context, id string) (booking.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingByID", ctx, id)
	ret0, _ := ret[0].(booking.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingByID indicates an expected call of GetBookingByID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingByID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingByID), ctx, id)
}

// GetBookingCountPerGame mocks base method.
func (m *MockBookingRepository) GetBookingCountPerGame(ctx context.Context) ([]booking.GameBookingCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingCountPerGame", ctx)
	ret0, _ := ret[0].([]booking.GameBookingCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingCountPerGame indicates an expected call of GetBookingCountPerGame.
func (mr *MockBookingRepositoryMockRecorder) GetBookingCountPerGame(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingCountPerGame", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingCountPerGame), ctx)
}

// GetBookingCountPerGameInPeriod mocks base method.
func (m *MockBookingRepository) GetBookingCountPerGameInPeriod(ctx context.Context, start, end time.Time) ([]booking.GameBookingCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingCountPerGameInPeriod", ctx, start, end)
	ret0, _ := ret[0].([]booking.GameBookingCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingCountPerGameInPeriod indicates an expected call of GetBookingCountPerGameInPeriod.
func (mr *MockBookingRepositoryMockRecorder) GetBookingCountPerGameInPeriod(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingCountPerGameInPeriod", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingCountPerGameInPeriod), ctx, start, end)
}

// GetBookingCountPerWeekDay mocks base method.
func (m *MockBookingRepository) GetBookingCountPerWeekDay(ctx context.Context) ([]booking.WeekDayBookingCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingCountPerWeekDay", ctx)
	ret0, _ := ret[0].([]booking.WeekDayBookingCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingCountPerWeekDay indicates an expected call of GetBookingCountPerWeekDay.
func (mr *MockBookingRepositoryMockRecorder) GetBookingCountPerWeekDay(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingCountPerWeekDay", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingCountPerWeekDay), ctx)
}

// GetBookingsPerUsername mocks base method.
func (m *MockBookingRepository) GetBookingsPerUsername(ctx context.Context, username string) ([]booking.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsPerUsername", ctx, username)
	ret0, _ := ret[0].([]booking.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsPerUsername indicates an expected call of GetBookingsPerUsername.
func (mr *MockBookingRepositoryMockRecorder) GetBookingsPerUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsPerUsername", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingsPerUsername), ctx, username)
}

// InsertBooking mocks base method.
func (m *MockBookingRepository) InsertBooking(ctx context.Context, arg1 booking.Booking) (booking.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBooking", ctx, arg1)
	ret0, _ := ret[0].(booking.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertBooking indicates an expected call of InsertBooking.
func (mr *MockBookingRepositoryMockRecorder) InsertBooking(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBooking", reflect.TypeOf((*MockBookingRepository)(nil).InsertBooking), ctx, arg1)
}

// SetBookingStatus mocks base method.
func (m *MockBookingRepository) SetBookingStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBookingStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBookingStatus indicates an expected call of SetBookingStatus.
func (mr *MockBookingRepositoryMockRecorder) SetBookingStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBookingStatus", reflect.TypeOf((*MockBookingRepository)(nil).SetBookingStatus), ctx, id, status)
}

// UpdateBooking mocks base method.
func (m *MockBookingRepository) UpdateBooking(ctx context.Context, arg1 booking.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBooking", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBooking indicates an expected call of UpdateBooking.
func (mr *MockBookingRepositoryMockRecorder) UpdateBooking(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBooking", reflect.TypeOf((*MockBookingRepository)(nil).UpdateBooking), ctx, arg1)
}
