// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hanksha/tbz-booking-system-backend/api (interfaces: BookingService)
//
// Generated by this command:
//
//      mockgen . BookingService
//

// Package mock_api is a generated GoMock package.
package mock_api

import (
        context "context"
        reflect "reflect"
        time "time"

        booking "github.com/hanksha/tbz-booking-system-backend/booking"
        discord "github.com/hanksha/tbz-booking-system-backend/discord"
        gomock "go.uber.org/mock/gomock"
)

// MockBookingService is a mock of BookingService interface.
type MockBookingService struct {
        ctrl     *gomock.Controller
        recorder *MockBookingServiceMockRecorder
        isgomock struct{}
}

// MockBookingServiceMockRecorder is the mock recorder for MockBookingService.
type MockBookingServiceMockRecorder struct {
        mock *MockBookingService
}

// NewMockBookingService creates a new mock instance.
func NewMockBookingService(ctrl *gomock.Controller) *MockBookingService {
        mock := &MockBookingService{ctrl: ctrl}
        mock.recorder = &MockBookingServiceMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingService) EXPECT() *MockBookingServiceMockRecorder {
        return m.recorder
}

// AcceptBooking mocks base method.
func (m *MockBookingService) AcceptBooking(ctx context.Context, id string) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "AcceptBooking", ctx, id)
        ret0, _ := ret[0].(error)
        return ret0
}

// AcceptBooking indicates an expected call of AcceptBooking.
func (mr *MockBookingServiceMockRecorder) AcceptBooking(ctx, id any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptBooking", reflect.TypeOf((*MockBookingService)(nil).AcceptBooking), ctx, id)
}

// CancelBooking mocks base method.
func (m *MockBookingService) CancelBooking(ctx context.Context, id string, user discord.DiscordUser) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CancelBooking", ctx, id, user)
        ret0, _ := ret[0].(error)
        return ret0
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockBookingServiceMockRecorder) CancelBooking(ctx, id, user any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockBookingService)(nil).CancelBooking), ctx, id, user)
}

// CreateBooking mocks base method.
func (m *MockBookingService) CreateBooking(ctx context.Context, arg1 booking.Booking) (booking.Booking, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CreateBooking", ctx, arg1)
        ret0, _ := ret[0].(booking.Booking)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockBookingServiceMockRecorder) CreateBooking(ctx, arg1 any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockBookingService)(nil).CreateBooking), ctx, arg1)
}

// FindBookingByID mocks base method.
func (m *MockBookingService) FindBookingByID(ctx context.Context, id string) (booking.Booking, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "FindBookingByID", ctx, id)
        ret0, _ := ret[0].(booking.Booking)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// FindBookingByID indicates an expected call of FindBookingByID.
func (mr *MockBookingServiceMockRecorder) FindBookingByID(ctx, id any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBookingByID", reflect.TypeOf((*MockBookingService)(nil).FindBookingByID), ctx, id)
}

// FindBookingsPerUsername mocks base method.
func (m *MockBookingService) FindBookingsPerUsername(ctx context.Context, username string) ([]booking.Booking, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "FindBookingsPerUsername", ctx, username)
        ret0, _ := ret[0].([]booking.Booking)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// FindBookingsPerUsername indicates an expected call of FindBookingsPerUsername.
func (mr *MockBookingServiceMockRecorder) FindBookingsPerUsername(ctx, username any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBookingsPerUsername", reflect.TypeOf((*MockBookingService)(nil).FindBookingsPerUsername), ctx, username)
}

// GetActiveBookings mocks base method.
func (m *MockBookingService) GetActiveBookings(ctx context.Context) ([]booking.Booking, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetActiveBookings", ctx)
        ret0, _ := ret[0].([]booking.Booking)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetActiveBookings indicates an expected call of GetActiveBookings.
func (mr *MockBookingServiceMockRecorder) GetActiveBookings(ctx any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveBookings", reflect.TypeOf((*MockBookingService)(nil).GetActiveBookings), ctx)
}

// GetBookingCountPerGame mocks base method.
func (m *MockBookingService) GetBookingCountPerGame(ctx context.Context) ([]booking.GameBookingCount, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetBookingCountPerGame", ctx)
        ret0, _ := ret[0].([]booking.GameBookingCount)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetBookingCountPerGame indicates an expected call of GetBookingCountPerGame.
func (mr *MockBookingServiceMockRecorder) GetBookingCountPerGame(ctx any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingCountPerGame", reflect.TypeOf((*MockBookingService)(nil).GetBookingCountPerGame), ctx)
}

// GetBookingCountPerGameInPeriod mocks base method.
func (m *MockBookingService) GetBookingCountPerGameInPeriod(ctx context.Context, start, end time.Time) ([]booking.GameBookingCount, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetBookingCountPerGameInPeriod", ctx, start, end)
        ret0, _ := ret[0].([]booking.GameBookingCount)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetBookingCountPerGameInPeriod indicates an expected call of GetBookingCountPerGameInPeriod.
func (mr *MockBookingServiceMockRecorder) GetBookingCountPerGameInPeriod(ctx, start, end any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingCountPerGameInPeriod", reflect.TypeOf((*MockBookingService)(nil).GetBookingCountPerGameInPeriod), ctx, start, end)
}

// GetBookingCountPerWeekDay mocks base method.
func (m *MockBookingService) GetBookingCountPerWeekDay(ctx context.Context) ([]booking.WeekDayBookingCount, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetBookingCountPerWeekDay", ctx)
        ret0, _ := ret[0].([]booking.WeekDayBookingCount)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetBookingCountPerWeekDay indicates an expected call of GetBookingCountPerWeekDay.
func (mr *MockBookingServiceMockRecorder) GetBookingCountPerWeekDay(ctx any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingCountPerWeekDay", reflect.TypeOf((*MockBookingService)(nil).GetBookingCountPerWeekDay), ctx)     
}

// ModifyBooking mocks base method.
func (m *MockBookingService) ModifyBooking(ctx context.Context, updated booking.Booking, user discord.DiscordUser) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "ModifyBooking", ctx, updated, user)
        ret0, _ := ret[0].(error)
        return ret0
}

// ModifyBooking indicates an expected call of ModifyBooking.
func (mr *MockBookingServiceMockRecorder) ModifyBooking(ctx, updated, user any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyBooking", reflect.TypeOf((*MockBookingService)(nil).ModifyBooking), ctx, updated, user)
}

// RefuseBooking mocks base method.
func (m *MockBookingService) RefuseBooking(ctx context.Context, id, reason string) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "RefuseBooking", ctx, id, reason)
        ret0, _ := ret[0].(error)
        return ret0
}

// RefuseBooking indicates an expected call of RefuseBooking.
func (mr *MockBookingServiceMockRecorder) RefuseBooking(ctx, id, reason any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefuseBooking", reflect.TypeOf((*MockBookingService)(nil).RefuseBooking), ctx, id, reason)
}